# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    #strategy:
      #matrix:
        #node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    #- name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v3
      #with:
        #node-version: ${{ matrix.node-version }}
        #cache: 'npm'
    #- run: npm ci
    #- run: npm run build
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy NodeJs app
        env:
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_KEY: ${{secrets.SSH_KEY}}
          SSH_USER: ${{secrets.SSH_USERNAME}}
        uses: appleboy/ssh-action@v0.1.4
        run: echo '$SSH_HOST'
        with:
          host: ${{env.SSH_HOST}}
          key: ${{env.SSH_KEY}}
          username: ${{env.SSH_USER}}
          port: 22
          
          script: |
            echo "running scripts"
            cd portfolio/html/myportfolio
            git pull
            npm run build